-- =============================================================================
-- 01-schema.sql: Complete PostgreSQL Schema Initialisation
-- =============================================================================

-- 1. DROP EXISTING TABLES (In reverse dependency order)
DROP TABLE IF EXISTS user_events CASCADE;
DROP TABLE IF EXISTS user_organisations CASCADE;
DROP TABLE IF EXISTS user_workout_preferences CASCADE;
DROP TABLE IF EXISTS organization_application CASCADE;
DROP TABLE IF EXISTS scheduled_call CASCADE;
DROP TABLE IF EXISTS feedback CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS callback_preference CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS organisation CASCADE;
DROP TABLE IF EXISTS workouts CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS trainers CASCADE;

-- 2. TRAINERS TABLE
CREATE TABLE trainers
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    prompt       VARCHAR(255),
    voice        VARCHAR(255),
    intro        VARCHAR(255),
    language     VARCHAR(255),
    image_select VARCHAR(255),
    image_call   VARCHAR(255),
    image_start  VARCHAR(255),
    ambience     VARCHAR(255)
);

-- 3. USERS TABLE
CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clerk_id        VARCHAR(255) NOT NULL UNIQUE,
    name            VARCHAR(255),
    role            VARCHAR(50), -- Enum: UserRole (USER, ADMIN, SUPER_ADMIN)
    intensity_level INT,
    context         TEXT,        -- Set to TEXT to avoid truncation
    trainer_id      BIGINT,
    city            VARCHAR(255),
    onboarding      BOOLEAN      NOT NULL DEFAULT true,
    fcm_token       VARCHAR(255)
);

-- 4. WORKOUTS TABLE
CREATE TABLE workouts
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255),
    instructions          TEXT, -- Mapped from @Column(columnDefinition = "TEXT")
    guidance              TEXT, -- Set to TEXT to avoid character varying(255) errors
    description           VARCHAR(255),
    dashboard_name        VARCHAR(255),
    dashboard_description TEXT, -- Mapped from @Column(columnDefinition = "TEXT")
    level                 INT,
    type                  VARCHAR(255),
    image                 VARCHAR(255),
    video                 VARCHAR(255),
    enabled               BOOLEAN NOT NULL DEFAULT true
);

-- 5. ORGANISATION TABLE
CREATE TABLE organisation
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    description     VARCHAR(255),
    users_following INT NOT NULL DEFAULT 0,
    org_city        VARCHAR(255),
    organizer_id    BIGINT,

    CONSTRAINT fk_organisation_organizer FOREIGN KEY (organizer_id) REFERENCES users (id) ON DELETE SET NULL
);

-- 6. EVENT TABLE
CREATE TABLE event
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    description     VARCHAR(255),
    time            TIMESTAMP WITH TIME ZONE,
    organisation_id BIGINT NOT NULL,
    city            VARCHAR(255),
    venue           VARCHAR(255),
    event_type      VARCHAR(255), -- Enum: EventType (IN_PERSON, ONLINE)
    users_attending INT    NOT NULL DEFAULT 0,

    CONSTRAINT fk_event_organisation FOREIGN KEY (organisation_id) REFERENCES organisation (id) ON DELETE CASCADE
);

-- 7. CALLBACK_PREFERENCE TABLE
CREATE TABLE callback_preference
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    callback_day  VARCHAR(255), -- Enum: DayOfWeekType
    callback_time TIME,
    repeat_type   VARCHAR(255), -- Enum: RepeatType (NEVER, WEEKLY)
    user_id       BIGINT,

    CONSTRAINT fk_callback_preference_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 8. ACTIVITY_LOG TABLE
CREATE TABLE activity_log
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    workout_id       BIGINT,
    completed_at     TIMESTAMP WITH TIME ZONE,
    duration_seconds INT,
    feedback         VARCHAR(255),
    status           VARCHAR(255)
);

CREATE INDEX idx_activity_log_user_id ON activity_log (user_id);
CREATE INDEX idx_activity_log_workout_id ON activity_log (workout_id);

-- 9. FEEDBACK TABLE
CREATE TABLE feedback
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    workout_id      BIGINT,
    activity_log_id BIGINT,
    difficulty      VARCHAR(255), -- Enum: FeedbackDifficulty
    liked           BOOLEAN,
    rating          INT,
    comment         VARCHAR(500), -- Mapped from @Column(length = 500)
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_feedback_user_id ON feedback (user_id);
CREATE INDEX idx_feedback_workout_id ON feedback (workout_id);
CREATE INDEX idx_feedback_activity_log_id ON feedback (activity_log_id);

-- 10. SCHEDULED_CALL TABLE
CREATE TABLE scheduled_call
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT,
    trainer_id       BIGINT,
    target_time      TIMESTAMP WITH TIME ZONE,
    fcm_token        VARCHAR(255),
    call_back_status VARCHAR(255) -- Enum: CallBackStatus
);

-- 11. ORGANIZATION_APPLICATION TABLE
CREATE TABLE organization_application
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    organization_name  VARCHAR(255),
    description        VARCHAR(2000), -- Mapped from @Column(length = 2000)
    city               VARCHAR(255),
    motivation         VARCHAR(2000), -- Mapped from @Column(length = 2000)
    application_status VARCHAR(255),  -- Enum: ApplicationStatus
    created_at         TIMESTAMP WITH TIME ZONE,
    reviewed_at        TIMESTAMP WITH TIME ZONE,
    payment_status     VARCHAR(255),  -- Enum: PaymentStatus

    CONSTRAINT fk_org_app_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 12. USER_WORKOUT_PREFERENCES TABLE
CREATE TABLE user_workout_preferences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    workout_id      BIGINT       NOT NULL,
    preference_type VARCHAR(255) NOT NULL, -- Enum: UserWorkoutPreferenceType
    created_at      TIMESTAMP WITH TIME ZONE,

    CONSTRAINT uk_user_workout_pref UNIQUE (user_id, workout_id, preference_type)
);

CREATE INDEX idx_user_workout_pref_user_id ON user_workout_preferences (user_id);
CREATE INDEX idx_user_workout_pref_workout_id ON user_workout_preferences (workout_id);

-- 13. JOIN TABLES (@ManyToMany relationships)
CREATE TABLE user_organisations
(
    user_id                   BIGINT NOT NULL,
    followed_organisations_id BIGINT NOT NULL,

    CONSTRAINT fk_user_org_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_org_organisation FOREIGN KEY (followed_organisations_id) REFERENCES organisation (id) ON DELETE CASCADE
);

CREATE TABLE user_events
(
    user_id             BIGINT NOT NULL,
    attending_events_id BIGINT NOT NULL,

    CONSTRAINT fk_user_event_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_event_event FOREIGN KEY (attending_events_id) REFERENCES event (id) ON DELETE CASCADE
);