INSERT INTO workouts (description, name, image, video, level, type, instructions, enabled,
                      dashboard_name, dashboard_description, guidance)
VALUES ('Mjuka axelrörelser för att minska spänning i nacke och axlar.',
        'Axelhöjningar', NULL, NULL, 1, 'MOBILITY',
        'Användaren ska stå eller sitta med rak rygg. Armarna ska vara avslappnade längs sidorna. Axlarna ska först höjas upp mot öronen och sedan sänkas ner mot marken. Viktigt att axlarna rör sig rakt upp och rakt ner och inte faller framåt. Vi gör 5 repetitioner.',
        TRUE,
        'Lätta axelhöjningar',
        'Mjuk rörelse för nacke och axlar.',
        'Guida användaren att höja axlarna och sedan sänka ner dem. Prata långsamt och med lite mellanrum. Säg till användaren när den ska höja axlarna och när den ska sänka axlarna. Totalt 5 repetitioner. De 3 första görs i vanlig takt. De 2 sista har en kort paus när axlarna är helt uppe och användaren ska försöka höja axlarna ännu en liten bit. Säg något uppmuntrande inför sista repetitionen.'),
       ('Mjuk träning för händer och fingrar.',
        'Handöppningar', NULL, NULL, 1, 'MOBILITY',
        'Användaren ska sitta eller stå med rak rygg och armarna avslappnade längs sidorna. Knyt båda händerna mjukt och öppna sedan händerna genom att sträcka ut fingrarna så mycket som känns bekvämt. Vi gör 6 repetitioner.',
        TRUE,
        'Öppna och stäng händerna',
        'En mjuk övning för fingrar och händer.',
        'Guida användaren att först knyta händerna mjukt och sedan öppna fingrarna brett. Prata lugnt och ge lite mellanrum mellan rörelserna. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren hålla händerna öppna en kort stund och försöka sträcka ut fingrarna lite extra. Säg något uppmuntrande inför sista repetitionen.'),
       ('En enkel sittande övning för vadmuskler och fotleder.',
        'Sittande tåhävningar', NULL, NULL, 1, 'STRENGTH',
        'Användaren ska sitta stadigt på en stol med båda fötterna i golvet och rak rygg. Lyft hälarna från golvet så att fötterna kommer upp på tå. Sänk sedan långsamt ner hälarna igen. Vi gör 6 repetitioner.',
        TRUE,
        'Tåhävningar på stol',
        'Stärk vader och fotleder sittande.',
        'Guida användaren att lyfta hälarna och sedan sänka ner dem med kontroll. Låt det vara lite mellanrum mellan repetitionerna. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna uppe på tå i två sekunder innan hälarna sänks igen. Säg något uppmuntrande inför sista repetitionen.'),
       ('Lugn sittande konditionsövning som aktiverar höfter och ben.',
        'Sittande marsch', NULL, NULL, 1, 'CARDIO',
        'Användaren ska sitta långt fram på en stadig stol med rak rygg och båda fötterna i golvet. Lyft växelvis ett knä några centimeter från golvet och sätt sedan ner foten igen. En höger- och vänsterlyft räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Marsch på stol',
        'Lugn aktivering av ben och höfter.',
        'Guida användaren att växelvis lyfta höger och vänster knä. Håll ett lugnt, jämnt tempo och påminn om att behålla en rak rygg. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren hålla varje knälyft en kort stund innan foten sätts ner. Säg något uppmuntrande inför sista repetitionen.'),
       ('Lätt pressövning för bröst, axlar och armar.',
        'Väggarmhävningar', NULL, NULL, 2, 'STRENGTH',
        'Användaren ska stå vänd mot en vägg, ungefär en armlängd från väggen. Placera händerna mot väggen i axelhöjd. Böj armbågarna och för kroppen mot väggen utan att svanka. Pressa sedan tillbaka till raka armar. Vi gör 6 repetitioner.',
        TRUE,
        'Armhävningar mot vägg',
        'Stärk överkroppen med stöd från väggen.',
        'Guida användaren att långsamt böja armarna och komma närmare väggen, och sedan pressa tillbaka till utgångsläget. Påminn om att hålla kroppen rak. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna nära väggen i två sekunder innan den pressar tillbaka. Säg något uppmuntrande inför sista repetitionen.'),
       ('Kontrollerade sidosteg som tränar balans och ben.',
        'Sidosteg med stöd', NULL, NULL, 2, 'CARDIO',
        'Användaren ska stå vid en stadig stol eller köksbänk och hålla lätt i stödet vid behov. Ta ett steg åt sidan och för sedan den andra foten intill utan att korsa fötterna. Gå åt båda håll. Ett steg åt höger och ett steg åt vänster räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Sidosteg',
        'Träna balans och rörelse i sidled.',
        'Guida användaren att ta små och kontrollerade sidosteg åt båda håll. Påminn om att titta framåt och använda stödet om balansen känns osäker. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren ta en kort paus med fötterna samlade mellan stegen. Säg något uppmuntrande inför sista repetitionen.'),
       ('Rörlighet för bröstkorg och skuldror.',
        'Bröstöppnare', NULL, NULL, 2, 'MOBILITY',
        'Användaren ska sitta eller stå med rak rygg. Armarna ska hänga längs sidorna med handflatorna riktade framåt. För armarna lätt bakåt och för skulderbladen mjukt mot varandra. Slappna sedan av och återgå till startpositionen. Vi gör 6 repetitioner.',
        TRUE,
        'Öppna bröstet',
        'Mjuk rörlighet för hållning och skuldror.',
        'Guida användaren att öppna upp över bröstet och föra skulderbladen mjukt mot varandra. Påminn om att axlarna ska vara nere och att rörelsen inte ska göra ont. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren hålla det öppna läget i två sekunder. Säg något uppmuntrande inför sista repetitionen.'),
       ('Stående övning som aktiverar höfter, mage och balans.',
        'Stående knälyft', NULL, NULL, 2, 'CARDIO',
        'Användaren ska stå nära en stadig stol eller köksbänk och använda stödet vid behov. Lyft växelvis ett knä framför kroppen till en bekväm höjd och sänk sedan ner foten. Ett höger- och vänsterlyft räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Knälyft stående',
        'Aktivera höfter och balans i stående.',
        'Guida användaren att växelvis lyfta höger och vänster knä och sedan sätta ner foten med kontroll. Påminn om att hålla överkroppen upprätt. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska varje knä hållas uppe en kort stund. Säg något uppmuntrande inför sista repetitionen.'),
       ('Funktionell styrkeövning för ben och säte.',
        'Resa sig från stol', NULL, NULL, 3, 'STRENGTH',
        'Användaren ska sitta långt fram på en stadig stol med fötterna höftbrett i golvet. Res dig upp till stående och sätt dig sedan långsamt ner igen. Knäna ska följa samma riktning som tårna. Armstöd får användas vid behov. Vi gör 6 repetitioner.',
        TRUE,
        'Res dig från stolen',
        'Stärk ben och säte med en vardagsrörelse.',
        'Guida användaren att luta sig lätt framåt, resa sig upp och sedan bromsa rörelsen på vägen ner till stolen. Påminn om att fötterna ska stå stadigt i golvet och att knäna inte faller inåt. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna stående i två sekunder innan den sätter sig. Säg något uppmuntrande inför sista repetitionen.'),
       ('Kontrollerad övning för säte och baksida lår.',
        'Benföring bakåt', NULL, NULL, 3, 'STRENGTH',
        'Användaren ska stå vid en stadig stol eller köksbänk och hålla lätt i stödet. För ett ben rakt bakåt utan att luta överkroppen framåt eller svanka mycket. För sedan tillbaka foten och byt ben. Ett lyft med varje ben räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'För benet bakåt',
        'Stärk säte och baksida lår med stöd.',
        'Guida användaren att föra ett ben bakåt och sedan återgå kontrollerat till startpositionen innan sidan byts. Påminn om att hålla höfterna riktade framåt. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska varje ben hållas bakåt i två sekunder. Säg något uppmuntrande inför sista repetitionen.'),
       ('Stående rörlighetsövning för höfter och baksida lår.',
        'Höftfällning', NULL, NULL, 3, 'MOBILITY',
        'Användaren ska stå med fötterna höftbrett isär och händerna på höfterna. Skjut höfterna bakåt med lätt böjda knän och fäll överkroppen framåt med rak rygg. Res dig sedan upp igen genom att föra höfterna framåt. Vi gör 6 repetitioner.',
        TRUE,
        'Fäll från höfterna',
        'Träna rörlighet och kontroll i höfter.',
        'Guida användaren att föra höfterna bakåt och sedan resa sig upp igen. Påminn om att hålla ryggen lång och neutral, och att rörelsen ska komma från höfterna. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna i det nedre läget i två sekunder. Säg något uppmuntrande inför sista repetitionen.'),
       ('Rytmisk helkroppsrörelse som höjer pulsen.',
        'Stående marsch med armdriv', NULL, NULL, 3, 'CARDIO',
        'Användaren ska stå upprätt med fötterna höftbrett isär. Marschera på stället genom att växelvis lyfta knäna och pendla med motsatt arm. Ett lyft med varje ben räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Marschera med armarna',
        'Få upp pulsen med ben och armar.',
        'Guida användaren att marschera på stället och låta motsatt arm följa med i rörelsen. Håll ett jämnt tempo och påminn om att stå upprätt. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren lyfta knäna lite högre om det känns stabilt. Säg något uppmuntrande inför sista repetitionen.'),
       ('Krävande benstyrka med större rörelseomfång.',
        'Djupa knäböj', NULL, NULL, 4, 'STRENGTH',
        'Användaren ska stå med fötterna ungefär axelbrett isär. Böj knän och höfter kontrollerat och sänk dig så djupt som rörlighet och kontroll tillåter, med hälarna kvar i golvet. Res dig sedan upp igen. Vi gör 6 repetitioner.',
        TRUE,
        'Djupa knäböj',
        'Utmanande styrka för ben och säte.',
        'Guida användaren att sänka sig kontrollerat och sedan pressa upp till stående igen. Påminn om att knäna följer tårnas riktning och att bröstet hålls öppet. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna i det nedre läget i två sekunder. Säg något uppmuntrande inför sista repetitionen.'),
       ('Styrketräning för ben och balans i ett större rörelseomfång.',
        'Utfall bakåt', NULL, NULL, 4, 'STRENGTH',
        'Användaren ska stå med fötterna höftbrett isär. Ta ett långt steg bakåt med ena foten och böj båda knäna kontrollerat. Pressa sedan tillbaka till stående med hjälp av det främre benet och byt sida. Ett utfall per sida räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Utfall bakåt',
        'Stärk ben och balans med kontrollerade utfall.',
        'Guida användaren genom rörelsen med ett tydligt steg bakåt, kontrollerat ner och sedan upp till stående igen. Påminn om att främre hälen hålls i golvet och att främre knät följer tårnas riktning. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna i det nedre läget i två sekunder. Säg något uppmuntrande inför sista repetitionen.'),
       ('Stabilitetsövning för mage, axlar och koordination.',
        'Planka med axelklapp', NULL, NULL, 4, 'STRENGTH',
        'Användaren ska stå i plankposition med händerna i golvet, armarna raka och kroppen i en så rak linje som möjligt. Lyft ena handen och rör lätt vid motsatt axel. Sätt tillbaka handen och gör samma sak med andra sidan. En klapp per sida räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Planka med axelklapp',
        'Stärk mage och axlar med stabilitetsträning.',
        'Guida användaren att växelvis lyfta en hand och röra vid motsatt axel. Påminn om att spänna magen, hålla ryggen stadig och försöka begränsa rörelsen i höfterna. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska handen hållas vid axeln i en sekund innan den sätts tillbaka. Säg något uppmuntrande inför sista repetitionen.'),
       ('Intensiv konditionsövning med snabb växling mellan ben.',
        'Mountain climbers', NULL, NULL, 4, 'CARDIO',
        'Användaren ska stå i plankposition med händerna i golvet. Dra växelvis ett knä mot magen och för tillbaka foten till plankposition. Ett knäindrag med varje ben räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Snabba knäindrag i planka',
        'Höj pulsen och utmana mage och axlar.',
        'Guida användaren att växelvis dra knäna mot magen och föra tillbaka fötterna. Håll ett raskt men kontrollerat tempo. Påminn om att hålla händerna under axlarna och ryggen så stadig som möjligt. De 4 första repetitionerna görs i jämn takt. De 2 sista görs något snabbare om tekniken fortfarande känns stabil. Säg något uppmuntrande inför sista repetitionen.'),
       ('Avancerad enbensstyrka som kräver rörlighet, balans och kontroll.',
        'Pistol squat till stol', NULL, NULL, 5, 'STRENGTH',
        'Användaren ska stå framför en stadig stol. Lyft ena foten från golvet och håll den framför kroppen. Böj långsamt i stödbenet och sänk kroppen mot stolen tills sätet lätt nuddar sitsen. Res dig sedan upp igen på samma ben. Byt ben efter varje repetition. Vi gör 4 repetitioner.',
        TRUE,
        'Enbensknäböj till stol',
        'Avancerad styrka och balans på ett ben.',
        'Guida användaren att först hitta balansen på ett ben, sedan långsamt sänka sig mot stolen och pressa sig tillbaka upp. Påminn om att knät följer tårnas riktning och att rörelsen ska vara kontrollerad hela vägen. De 2 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna precis ovanför stolen i två sekunder innan den reser sig. Säg något uppmuntrande inför sista repetitionen.'),
       ('Avancerad explosiv helkroppsövning med styrka och kondition.',
        'Burpee med armhävning', NULL, NULL, 5, 'CARDIO',
        'Användaren ska stå med fötterna höftbrett isär. Böj ner och placera händerna i golvet. Hoppa bak med fötterna till plankposition, gör en armhävning, hoppa fram med fötterna och res dig upp. Avsluta med ett hopp och armarna uppåt. Vi gör 6 repetitioner.',
        TRUE,
        'Burpee med armhävning',
        'Explosiv helkroppsträning för styrka och puls.',
        'Guida användaren tydligt genom varje del av rörelsen: ner med händerna, bak till planka, armhävning, fram med fötterna, res upp och avsluta med hopp. Låt användaren kort hitta stabilitet i plankpositionen. De 4 första repetitionerna görs i jämn takt. På de 2 sista ska användaren hålla plankpositionen i två sekunder före armhävningen. Säg något uppmuntrande inför sista repetitionen.'),
       ('Avancerad enbensövning för balans, höfter och baksida lår.',
        'Enbensmarklyft utan vikt', NULL, NULL, 5, 'STRENGTH',
        'Användaren ska stå på ett ben med lätt böjt stödknä. Fäll kroppen framåt från höften samtidigt som det fria benet förs rakt bakåt. Håll ryggen lång och för sedan kroppen tillbaka till stående. Byt ben efter varje repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Enbensmarklyft',
        'Avancerad balans och styrka för höfter och baksida lår.',
        'Guida användaren att först hitta balansen och sedan fälla framåt från höften medan det fria benet förs bakåt. Påminn om att hålla höften så rak som möjligt och röra sig långsamt. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren stanna i det framfällda läget i två sekunder. Säg något uppmuntrande inför sista repetitionen.'),
       ('Avancerad bålövning som kräver stark mage och god kroppskontroll.',
        'Hollow hold med bensträck', NULL, NULL, 5, 'STRENGTH',
        'Användaren ska ligga på rygg med armarna sträckta bakom huvudet och benen sträckta. Spänn magen och lyft skuldror och ben från golvet. För sedan ett knä i taget mot magen och sträck tillbaka benet, utan att tappa spänningen i bålen. Ett knäindrag per sida räknas som en repetition. Vi gör 6 repetitioner.',
        TRUE,
        'Hollow hold med ben',
        'Utmanande bålstyrka och kroppskontroll.',
        'Guida användaren att hitta en stabil hollow hold med magen spänd och ländryggen nära golvet. Guida sedan växelvis knäindrag utan att överkroppen tappar sin position. De 4 första repetitionerna görs i vanlig takt. På de 2 sista ska användaren hålla det utsträckta benet en kort stund innan nästa knäindrag. Säg något uppmuntrande inför sista repetitionen.');